title:  "vtt.bzh"
headline: "Calendrier Rando VTT Bretagne"
local: "fr_FR"
description: "Calendrier des randonnées VTT de Bretagne | VTT.bzh. Morbihan, finistère, Ille et Vilaine, Cotes d'armor, Loire Atlantique, programmer des maintenant votre prochaine rando VTT du week-end."
keywords: "randonnée, rando, randonnées, vtt, rando vtt, rando vtt bretagne"
main_image: "assets/public/images/banner-min.jpg"
url: "https://vtt.bzh"

# disqus
comments:
  disqus: 
    shortname: 'nicolasjouanno-com'  
    
# Outputting
permalink : /:title:output_ext
paginate: 12
paginate_path: /blog/page:num/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  # - jekyll-archives  
  # - jekyll-minifier

whitelist:
  - jekyll-paginate
    
# Archives
# jekyll-archives:
#   enabled:
#    - categories
#  layout: archive
#  permalinks:
#    category: '/:name/'
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Minification
# jekyll-minifier:
#   exclude: 'feed.xml'
    
# Other
markdown: kramdown
highlighter: rouge
future: false
sass:
  style: compact # possible values: nested expanded compact compressed
